### PR TITLE
adding .spi.yml file to opt into documentation for SwiftPackageIndex

### PR DESCRIPTION
**Pull request by heckj**
This adds in the .spi.yml file that will opt you in to hosted documentation for [your project at the Swift Package Index](https://swiftpackageindex.com/wigging/numerix).

### CODE REVIEW

**Comment by wigging** [comment]
This is on my to-do list but haven't gotten around to it yet. Thanks for taking the initiative to get it started. The [Compatibility](https://swiftpackageindex.com/wigging/numerix) table doesn't seem right. I don't think I specified it as supporting visionOS in the manifest file.

**Comment by wigging** [comment]
Why did you define a `scheme`? I think `documentation_targets` is the only thing needed in the file.

**Comment by heckj** [comment]
It probably is the only that that's required - I copied from another project of mine where I've done the same, and since it had it, i just rolled with it. I can trim it out if you'd prefer.

**Comment by heckj** [comment]
> This is on my to-do list but haven't gotten around to it yet. Thanks for taking the initiative to get it started. The [Compatibility](https://swiftpackageindex.com/wigging/numerix) table doesn't seem right. I don't think I specified it as supporting visionOS in the manifest file.

I think you're hitting a common misconception of the availability setup. The values declared in Package.swift ONLY specify the minimum OS versions, with the base-line assumption that a package is available for "the earliest version of any platform that the Swift-tools version of the package supports". That's a mouthful for a crap-ton of confusion, but the end result is you get all support by default, and within Package.swift, there's no way to assert "I'm not supporting platform X", which is annoying as all get out (to me).

**Comment by wigging** [comment]
Let's just go with:
```yaml
version: 1
builder:
  configs:
    - documentation_targets: [Numerix]
```

Regarding the `Package.swift` file, it contains the following:
```swift
platforms: [
    .macOS(.v14),
    .iOS(.v16)
]
```
Which I thought would restrict the package to macOS 14 and up along with iOS 16 and higher. But based on your comment, this just means the minimum for those particular versions while other operating systems are still supported even if they aren't explicitly listed in `platforms`.

**Comment by heckj** [comment]
> Which I thought would restrict the package to macOS 14 and up along with iOS 16 and higher. But based on your comment, this just means the minimum for those particular versions while other operating systems are still supported even if they aren't explicitly listed in `platforms`.

Yep, correct. I have a library up that I wanted to make clear _wasn't_ supported on Linux, for example. My workaround (that Sven from SPI suggested) is [basically a poison-pill in the build](https://github.com/automerge/automerge-swift/blob/main/Sources/Automerge/_AutomergeLinux.swift) that failed any build on Linux using a `#if os(Linux)` block.

**Comment by wigging** [comment]
Yeah, the platforms parameter is very misleading. Well thanks for the contribution. I'll go ahead and merge with the main branch.

**Pull request merged**
